// Downloads webfonts from Google Fonts and rewrites the CSS to local paths, so
// the app keeps working with no network. Re-runnable: it is the single source
// of truth for what lives in web/fonts/.
import { writeFileSync, mkdirSync, existsSync, readdirSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';
const FAMILIES = [
  // Display: variable soft-serif, optical sizing. Carries money figures and titles.
  'Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,300..700,0..100,0..1',
  // UI: grotesque drawn for small sizes, real tabular figures.
  'Archivo:ital,wdth,wght@0,62..125,100..900;1,62..125,100..900',
];
const ICONS = process.argv.includes('--icons');

mkdirSync('web/fonts', { recursive: true });
// NOTE: the old directory is NOT cleared here. It used to be, and a failed
// fetch then left web/fonts EMPTY — the app loses its typeface and its icons
// for a reason that has nothing to do with the app. Nothing is deleted until
// every replacement byte is in hand; see the swap below.

let css = '';
for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(fam).replace(/%3A/g,':').replace(/%40/g,'@').replace(/%2C/g,',').replace(/%3B/g,';')}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) { console.error(`  FAIL ${fam}: HTTP ${res.status}`); process.exit(1); }
  css += await res.text() + '\n';
}

// Icon font, subset to exactly the glyphs the markup uses.
let iconNames = '';
if (ICONS) {
  // Derived, never typed. See scripts/icon-names.mjs for why.
  const names = process.env.ICON_NAMES
    || execFileSync('node', ['scripts/icon-names.mjs'], { encoding: 'utf8' }).trim();
  iconNames = names;
  console.log(`  icon subset: ${names.split(',').length} glyphs`);
  const res = await fetch(`https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=${names}&display=block`,
                          { headers: { 'User-Agent': UA } });
  if (!res.ok) { console.error(`  FAIL icons: HTTP ${res.status}`); process.exit(1); }
  css += await res.text() + '\n';
}

const urls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/g)].map(m => m[1]))];
let out = css, total = 0;
const fetched = [];
for (const u of urls) {
  const bin = Buffer.from(await (await fetch(u, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const fam = (u.match(/\/s\/([a-z0-9]+)\//) || [,'font'])[1];
  const name = `${fam}-${total}.woff2`;
  fetched.push([name, bin]);
  out = out.split(u).join(`fonts/${name}`);
  total += bin.length ? 1 : 0;
  console.log(`  ${name.padEnd(28)} ${(bin.length/1024).toFixed(0)} KB`);
}
if (!fetched.length) { console.error('  FAIL: no font files fetched; leaving web/fonts untouched'); process.exit(1); }

// Every byte is in hand — only now is it safe to replace what is on disk.
for (const f of readdirSync('web/fonts')) unlinkSync(path.join('web/fonts', f));
for (const [name, bin] of fetched) writeFileSync(path.join('web/fonts', name), bin);
writeFileSync('web/fonts.css',
`/* Generated by scripts/vendor-fonts.mjs — do not edit by hand.
   icon_names=${iconNames}
   Served from disk so the app renders with no network. */\n` + out);
console.log(`\n  ${total} files, fonts.css written, remote urls left: ${(out.match(/https:\/\//g)||[]).length}`);
